name = "kertmen-website"
compatibility_date = "2025-05-05"
main = "./workers-site/index.js"
account_id = ""

[site]
bucket = "./out"

[build]
command = "pnpm run build"

[env.production]
routes = [
  { pattern = "kertmen.com.tr/*", zone_id = "" }
] 