name = "kertmen-website"
main = "./.next/server/app/page.js"
compatibility_date = "2025-05-05"

[site]
bucket = "./out"

[build]
command = "pnpm run build"
output_directory = "out"

[env.production]
routes = [
  { pattern = "/*", zone_name = "kertmen.com.tr" }
] 